<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <PropertyGroup>
        <!-- Root Namespace -->
        <RootNamespace>PPWCode.API.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="PPWCode.Vernacular.Exceptions.IV"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson"/>
    </ItemGroup>

</Project>
