<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>

    <!-- Root Namespace -->
    <RootNamespace>PPWCode.API.Core</RootNamespace>

    <!-- nuget package -->
    <IsPackable>true</IsPackable>

    <!-- Stylecop -->
    <CodeAnalysisRuleSet>..\StyleCop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="4.4.1" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\PPWCode.API.Core.NewtonSoft\PPWCode.API.Core.NewtonSoft.csproj" />
  </ItemGroup>

</Project>
