<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <PropertyGroup>
        <!-- Root Namespace -->
        <RootNamespace>PPWCode.API.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PPWCode.API.Core.NewtonSoft\PPWCode.API.Core.NewtonSoft.csproj"/>
    </ItemGroup>

</Project>
